using System;
using System.Collections.Generic;
using System.Text;
using ElectricityBilling.Domain.Basics;
using NWheelsTempApiLib;

namespace ElectricityBilling.Domain.Customers
{
    public class CustomerEntity
    {
        [MemberContract.EntityId, MemberContract.AutoGenerated]
        public long Id { get; }

        public string PersonIdentity { get; set; }

        public PersonNameValueObject PersonName { get; set; }

        public IList<ContactDetailValueObject> ContactDetails { get; }

        public PostalAddressValueObject BillingAddress { get; set; }
    }
}
