using System;
using System.Collections.Generic;
using System.Text;
using ElectricityBilling.Domain.Basics;
using ElectricityBilling.Domain.Billing;
using NWheels;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Customers
{
    public class CustomerEntity
    {
        [MemberContract.EntityId, MemberContract.AutoGenerated]
        public long Id { get; }

        public string PersonIdentity { get; set; }

        public ValueObject<PersonNameValueObject> PersonName { get; set; }

        //TODO: add validation that one and only one contact detail's IsPrimary is true
        public ValueObjectList<ContactDetailValueObject> ContactDetails { get; }

        public ValueObject<PostalAddressValueObject> BillingAddress { get; set; }

        public EntitySet<long, ContractEntity> Contracts { get; }
    }
}
