using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using ElectricityBilling.Domain.Basics;
using ElectricityBilling.Domain.Billing;
using NWheels;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Customers
{
    public class CustomerEntity
    {
        [MemberContract.EntityId, MemberContract.AutoGenerated]
        private readonly long _id;

        [MemberContract.Validation.MaxLength(50)]
        private string _personIdentity;

        [MemberContract.Semantics.EmailAddress]
        private string _emailAddress;

        private PersonNameValueObject _personName;

        [MemberContract.Semantics.Culture]
        private string _culture;

        private readonly List<ContactDetailValueObject> _contactDetails = new List<ContactDetailValueObject>();

        private PostalAddressValueObject _billingAddress;

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public CustomerEntity(string personIdentity, string emailAddress, PersonNameValueObject personName, PostalAddressValueObject billingAddress)
        {
            _personIdentity = personIdentity;
            _emailAddress = emailAddress;
            _personName = personName;
            _billingAddress = billingAddress;
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public long Id => _id;
        public string PersonIdentity => _personIdentity;
        public string EmailAddress => _emailAddress;

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public PersonNameValueObject PersonName
        {
            get => _personName;
            set => _personName = value;
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public string Culture
        {
            get => _culture;
            set => _culture = value;
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public List<ContactDetailValueObject> ContactDetails => _contactDetails;

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public PostalAddressValueObject BillingAddress
        {
            get => _billingAddress;
            set => _billingAddress = value;
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public struct Ref
        {
            public readonly long Id;
            #region Generated code
            public Ref(long id) => this.Id = id;
            public static implicit operator Ref(CustomerEntity entity) => new Ref(entity.Id);
            public static implicit operator Ref(long id) => new Ref(id);
            #endregion
        }
    }
}
