using System;
using NWheels.Api;
using NWheels.Api.Ddd;

namespace ExpenseTracker.Domain.Entities
{
    [DomainModel.Entity]
    public class Category
    {
        [DomainModel.PersistedProperty(AutoGenerated = true)]
        public virtual Guid Id { get; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual string Name { get; set; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual Category Parent { get; set; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual bool IsProrated  { get; set; }    
    }
}