using System;
using NWheels.Api;
using NWheels.Api.Ddd;

namespace ExpenseTracker.Domain.Entities
{
    [DomainModel.Entity]
    public class Transaction
    {
        [DomainModel.PersistedProperty(AutoGenerated = true)]
        public virtual Guid Id { get; set; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual DateTime Date { get; set; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual decimal Amount { get; set; }    

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [DomainModel.PersistedProperty]
        public virtual string Memo { get; set; }
    }
}