using System;
using System.Collections.Generic;
using System.Text;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Accounts
{
    public abstract class UserAccountEntity
    {
        [NWheels.MemberContract.AutoGenerated]
        private readonly long _id;
        private readonly List<UserCredentialValueObject> _credentials = new List<UserCredentialValueObject>();

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public long Id => _id;
        public List<UserCredentialValueObject> Credentials => _credentials;

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public struct Ref
        {
            public readonly long Id;
            public Ref(long id) => this.Id = id;
        }
    }
}
