using System;
using System.Collections.Generic;
using System.Text;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Accounts
{
    public abstract class UserAccountEntity
    {
        [NWheels.MemberContract.AutoGenerated]
        public long Id { get; }

        public ValueObject<UserCredentialsValueObject> Credentials { get; protected set; }
    }
}
