using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace NWheels
{
    public interface IOperatingSystemEnvironment
    {
        DateTime UtcNow { get; }
    }

    public static class TypeContract
    {
        public static class Presentation
        {
            public class DefaultFormatAttribute : Attribute
            {
                public DefaultFormatAttribute(string formatPattern)
                {
                }
            }
        }

        public class DataTransferObject : Attribute
        {
        }

        public class InjectorAttribute : Attribute
        {
        }
    }

    public static class ParameterContract
    {
        public class InjectedDependencyAttribute : Attribute
        {
        }
    }

    public static class MemberContract
    {
        public class TransientAttribute : Attribute
        {
        }
        public class PersistentAttribute : Attribute
        {
            public PersistentAttribute(bool isPersistent = true)
            {
            }
        }
        public class InjectedDependencyAttribute : Attribute
        {
        }
        public class AutoGeneratedAttribute : Attribute
        {
            public AutoGeneratedAttribute()
            {
            }
            public string ValueFormatString { get; set; }
            public GeneratedValueOption Option { get; set; }
        }
        public class EntityIdAttribute : Attribute
        {
        }
        public class RequiredAttribute : Attribute
        {
            public RequiredAttribute(bool allowEmpty = false)
            {
            }
        }

        public static class Semantics
        {
            public class StartRangeAttribute : Attribute
            {
                public StartRangeAttribute()
                {
                }
                public string EndMember { get; set; }
            }
            public class EmailAddressAttribute : Attribute
            {
            }
            public class PhoneNumberAttribute : Attribute
            {
            }
            public class CurrencyAttribute : Attribute
            {
            }
            public class UtcAttribute : Attribute
            {
            }
            public class PasswordClearAttribute : Attribute
            {
                public bool ShouldConfirm { get; set; }
            }
            public class SensitiveCipherAttribute : Attribute
            {
            }
            public class StreetAttribute : Attribute
            {
            }
            public class StreetNumberAttribute : Attribute
            {
            }
            public class CityAttribute : Attribute
            {
            }
            public class CountryStateAttribute : Attribute
            {
            }
            public class CountryAttribute : Attribute
            {
            }
            public class CountyAttribute : Attribute
            {
            }
            public class ZipCodeAttribute : Attribute
            {
            }
            public class DateTimeResolutionAttribute : Attribute
            {
                public DateTimeResolutionAttribute(DateTimeResolution resolution)
                {
                }
            }
            public class DayOfWeekAttribute : Attribute
            {
            }
            public class DayOfMonthAttribute : Attribute
            {
            }
            public class MonthAttribute : Attribute
            {
            }
            public class YearAttribute : Attribute
            {
            }
            public class CultureAttribute : Attribute
            {
            }
        }

        public static class Validation
        {
            public class NonNegativeAttribute : Attribute
            {
            }
            public class UniqueAttribute : Attribute
            {
            }
            public class MaxLength : Attribute
            {
                public MaxLength(int length)
                {
                }
            }
            public class GreaterThanMember : Attribute
            {
                public GreaterThanMember(string memberName)
                {
                }
            }
        }

        public static class Presentation
        {
            public class DefaultObjectDisplayAttribute : Attribute
            {
                public DefaultObjectDisplayAttribute()
                {
                }
                public DefaultObjectDisplayAttribute(string formatPattern)
                {
                }
            }

            public class HiddenAttribute : Attribute
            {
            }
        }
    }

    public enum GeneratedValueOption
    {
        Default,
        Application,
        Database
    }

    public enum DateTimeResolution
    {
        Years,
        Months,
        Days,
        Hours,
        Minutes,
        Seconds
    }

    namespace Authorization
    {
        public static class SecurityContract
        {
            public class AllowAnonymousAttribute : Attribute
            {
            }

            public class Require : Attribute
            {
                public Require(object claim)
                {
                    this.Claim = claim;
                }

                public object Claim { get; }
            }
        }
    }
}

