using System;
using System.Collections.Generic;
using System.Text;
using NWheels;

namespace ElectricityBilling.Domain.Payments
{
    public abstract class PaymentMethodEntity
    {
        [MemberContract.AutoGenerated]
        public long Id { get; }

        [MemberContract.Required]
        [MemberContract.Validation.Unique]
        [MemberContract.Presentation.DefaultObjectDisplay]
        public string Title { get; set; }

        //protected 
    }
}
