using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using NWheels;

namespace ElectricityBilling.Domain.Payments
{
    public abstract class PaymentMethodEntity
    {
        [MemberContract.AutoGenerated]
        private readonly long _id;

        [MemberContract.Required]
        [MemberContract.Validation.Unique]
        [MemberContract.Presentation.DefaultObjectDisplay]
        private string _title;

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        protected PaymentMethodEntity(Injector injector, string title)
        {
            injector.Inject(this, out _id);
            _title = title;
        }
        
        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public abstract Task<PaymentProcessingResult> ProcessPaymentAsync(); 

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public long Id => _id;

        public string Title
        {
            get => _title;
            set => _title = value;
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        public struct Ref
        {
            public readonly long Id;
            #region Generated code
            public Ref(long id) => this.Id = id;
            public static implicit operator Ref(PaymentMethodEntity entity) => new Ref(entity.Id);
            #endregion
        }
    }
}
