using System;
using System.Collections.Generic;
using System.Text;
using ElectricityBilling.Domain.Basics;
using ElectricityBilling.Domain.Customers;
using NWheels;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Payments
{
    [NWheels.TypeContract.Presentation.DefaultFormat("{DateTime:}")]
    public class ReceiptEntity
    {
        [MemberContract.AutoGenerated]
        public long Id { get; }

        public EntityRef<long, CustomerEntity> Customer { get; }

        public EntityRef<long, PaymentMethodEntity> PaymentMethod { get; }

        // amount the customer was charged, in the exact currency the customer paid with
        public MoneyValueObject AmountPaid { get; }

        // this is an internal value for the operator; it isn't displayed to the customer
        // this is amount converted to operator's currency, with payment processing fees deducted
        public MoneyValueObject AmountReceived { get; }

        [MemberContract.Semantics.Utc]
        public DateTime DateTime { get; }

        [MemberContract.Validation.MaxLength(512)]
        public string Memo { get; set; }
    }
}
