using static NWheels.Domain.Model.ValueContract;

namespace Demo.TodoList.Domain
{
    public class TodoItemEntity
    {
        [AutoGenerated]
        public readonly int Id;
        
        [Required, Unique, MaxLength(100)]
        public string Title;

        public bool Done;
    }
}
