using System;
using ElectricityBilling.Domain.Sensors;
using NWheels;
using NWheels.Ddd;

namespace ElectricityBilling.Domain.Billing
{
    public class ContractEntity
    {
        [MemberContract.AutoGenerated]
        public long Id { get; }

        public DateTime ValidFrom { get; }
        public DateTime? ValidUntil { get; private set; }

        public EntityRef<string, SensorEntity> Sensor { get; }
        public EntityRef<long, PricingPlanEntity> PricingPlan { get; }
    }
}
