using System;
using System.Collections.Generic;
using System.Text;
using NWheelsTempApiLib;

namespace ElectricityBilling.Domain.Billing
{
    public abstract class PricingPlanEntity
    {
        public abstract decimal GetDailyCharge(decimal consumptionKwh, DateTime startUtc, DateTime finishUtc);

        [MemberContract.AutoGenerated]
        public long Id { get; }

        [MemberContract.Required]
        public string Description { get; set; }
    }

    //---------------------------------------------------------------------------------------------------------------------------------------------------------

    //public class FlatPricingPlanEntity : PricingPlanEntity
    //{

    //}
}
