using System;

namespace NWheels.Api.Ddd
{
    public static class DomainModel
    {
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, Inherited = true, AllowMultiple = false)]
        public sealed class BoundedContextAttribute : System.Attribute
        {
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, Inherited = true, AllowMultiple = false)]
        public sealed class EntityAttribute : System.Attribute
        {
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, Inherited = true, AllowMultiple = false)]
        public sealed class ValueObjectAttribute : System.Attribute
        {
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
        public sealed class PersistedPropertyAttribute : System.Attribute
        {
            public bool AutoGenerated { get; set; }
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
        public sealed class CalculatedPropertyAttribute : System.Attribute
        {
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
        public sealed class InjectedDependencyAttribute : System.Attribute
        {
        }

        //-----------------------------------------------------------------------------------------------------------------------------------------------------

        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
        public sealed class DomainEventFilterAttribute : System.Attribute
        {
            public string SelectOneMethod { get; set; }
            public string SelectManyMethod { get; set; }
        }
    }
}
